### ISSUE TITLE
Setup on rasperberry pi

### ISSUE THREAD

**Issue by OpenSystemCode** [KanoczTomas/01Cnode#53]
Hey Guys,

I want to install this project on my raspberry pi. (PI Setup Guide by Stadicus: https://github.com/Stadicus/guides/tree/master/raspibolt)

OS: Raspbian Stretch Lite 
Bitcoin Full Node : 17.0

I followed the instructions. I stuck at npm install cmd.

Log output:

```
Succesfully build libzmq on Fri Apr 19 2019 15:00:50 GMT+0200 (Central European Summer Time)
make: Entering directory '/home/admin/bitcoin-dashboard/node_modules/zeromq/build'
  CXX(target) Release/obj.target/zmq/binding.o
In file included from ../../nan/nan.h:192:0,
                 from ../binding.cc:40:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:198,
                 from ../binding.cc:40:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:337:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/admin/.node-gyp/11.14.0/include/node/v8.h:26:0,
                 from ../binding.cc:24:
/home/admin/.node-gyp/11.14.0/include/node/v8.h:5242:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/home/admin/.node-gyp/11.14.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE ’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../binding.cc:25:0:
/home/admin/.node-gyp/11.14.0/include/node/node.h:174:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/admin/.node-gyp/11.14.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../binding.cc:25:0:
/home/admin/.node-gyp/11.14.0/include/node/node.h:167:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/admin/.node-gyp/11.14.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../binding.cc:25:0:
/home/admin/.node-gyp/11.14.0/include/node/node.h:160:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/admin/.node-gyp/11.14.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:911:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from ../binding.cc:24:0:
/home/admin/.node-gyp/11.14.0/include/node/v8.h:10251:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h:921:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/admin/.node-gyp/11.14.0/include/node/v8.h:26:0,
                 from ../binding.cc:24:
/home/admin/.node-gyp/11.14.0/include/node/v8.h:2754:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/home/admin/.node-gyp/11.14.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE ’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../binding.cc:40:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../binding.cc:25:0:
/home/admin/.node-gyp/11.14.0/include/node/node.h:174:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/admin/.node-gyp/11.14.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
zmq.target.mk:99: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/home/admin/bitcoin-dashboard/node_modules/zeromq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.14.70-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/bitcoin-dashboard/node_modules/zeromq
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Nodejs Stuff:

~ $ node -v
11.14.0

 $ npm -v
v6.7.0

Can someone help me?

Best regards.

**Comment by Hansie020** [comment]
I have exactly the same problem. I tried the following that did not work:
`sudo apt-get install build-essential checkinstall`
`npm install -g node-gyp`
` sudo apt-get install libzmq-dev`

Any suggestions would be great!

**Comment by KanoczTomas** [comment]
Hi! Did you @OpenSystemCode  or @Hansie020 try the docker installation on the raspberry Pi? Would be nice to try if it is the environment or something else. 

I do not have a raspberry Pi now, I will try getting one in the following days.

**Comment by Hansie020** [comment]
Hi, I got the webserver runnning with the docker install scripts but it does not show any data. I am running bitcoin core deamon on the same raspberry pi. I have installed a firewall so that might be a problem. Do I have to add a rule to let the docker image connect to the bitcoind process?

The server log is unreachable for me. The folder /opt/01cnode/ does not exists on my pi.

Any suggestions are appreciated.

**Comment by KanoczTomas** [comment]
The server log is in the docker container. You should read up more about docker.
E.g. here is a guide how to connect to docker: https://www.shellhacks.com/docker-enter-container/

And yes you should have port 5000 opened on your firewall.

Is the webpage empty, e.g. not loading at all, or just not functioning properly?

**Comment by Hansie020** [comment]
Thanks for the tip. The log dir is empty though.
The websites loads but does not show any blockchain data. 
<img width="1440" alt="Screenshot 2019-06-12 at 22 01 22" src="https://user-images.githubusercontent.com/36500271/59382298-af0f4800-8d5d-11e9-9946-582e8c92b3af.png">

It looks more like the rpc connection is not functioning well
